package dnsboot

import (
	"reflect"
	"strings"
	"testing"
)

func TestHexLEToIP(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{name: "doc example", in: "0101A8C0", want: "192.168.1.1"},
		{name: "placeholder gateway", in: "010200C0", want: "192.0.2.1"},
		{name: "high last octet", in: "FE0200C0", want: "192.0.2.254"},
		{name: "lowercase hex accepted", in: "010200c0", want: "192.0.2.1"},
		{name: "zero address means no gateway", in: "00000000", want: ""},
		{name: "empty string", in: "", want: ""},
		{name: "not hex", in: "notahex1", want: ""},
		{name: "wider than 32 bits", in: "1010200C0", want: ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := hexLEToIP(tc.in); got != tc.want {
				t.Fatalf("hexLEToIP(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

func TestParseNameservers(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want []string
	}{
		{
			name: "empty file (the fault this package exists for)",
			in:   "",
			want: nil,
		},
		{
			name: "typical dhcp-written file",
			in:   "# Generated by dhcpcd\ndomain lan\nnameserver 192.0.2.1\nnameserver 192.0.2.53\n",
			want: []string{"192.0.2.1", "192.0.2.53"},
		},
		{
			name: "our own bootstrap file round-trips",
			in:   "# written by STM (dnsboot): the box had no usable nameserver.\nnameserver 192.0.2.1\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n",
			want: []string{"192.0.2.1", "1.1.1.1", "8.8.8.8"},
		},
		{
			name: "leading whitespace and crlf line endings",
			in:   "  nameserver 192.0.2.1\r\n\tnameserver 192.0.2.2\r\n",
			want: []string{"192.0.2.1", "192.0.2.2"},
		},
		{
			name: "tab between keyword and value",
			in:   "nameserver\t192.0.2.1\n",
			want: []string{"192.0.2.1"},
		},
		{
			name: "bare keyword without a value is skipped",
			in:   "nameserver\nnameserver 192.0.2.1\n",
			want: []string{"192.0.2.1"},
		},
		{
			name: "commented-out nameserver is skipped",
			in:   "#nameserver 192.0.2.1\n# nameserver 192.0.2.2\n",
			want: nil,
		},
		{
			name: "search domain and options only, no resolver",
			in:   "search lan\noptions timeout:2\n",
			want: nil,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := parseNameservers(tc.in); !reflect.DeepEqual(got, tc.want) {
				t.Fatalf("parseNameservers(%q) = %#v, want %#v", tc.in, got, tc.want)
			}
		})
	}
}

// routeHeader is the first line of /proc/net/route as the kernel prints it
// (note the trailing space after "Gateway" and the double tab after "Mask").
const routeHeader = "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\t\tMTU\tWindow\tIRTT\n"

func TestDefaultGatewayFrom(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "captured shape with default route",
			in: routeHeader +
				"mlan0\t00000000\t010200C0\t0003\t0\t0\t0\t00000000\t0\t0\t0\n" +
				"mlan0\t000200C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\t0\t0\t0\n",
			want: "192.0.2.1",
		},
		{
			name: "subnet route only, no default route",
			in: routeHeader +
				"mlan0\t000200C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\t0\t0\t0\n",
			want: "",
		},
		{
			name: "empty input",
			in:   "",
			want: "",
		},
		{
			name: "header only",
			in:   routeHeader,
			want: "",
		},
		{
			name: "zero-gateway default route is skipped, later real one wins",
			in: routeHeader +
				"tun0\t00000000\t00000000\t0001\t0\t0\t0\t00000000\t0\t0\t0\n" +
				"mlan0\t00000000\t010200C0\t0003\t0\t0\t0\t00000000\t0\t0\t0\n",
			want: "192.0.2.1",
		},
		{
			name: "short malformed line is skipped",
			in: routeHeader +
				"mlan0\t00000000\n" +
				"mlan0\t00000000\t010200C0\t0003\t0\t0\t0\t00000000\t0\t0\t0\n",
			want: "192.0.2.1",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := defaultGatewayFrom(strings.NewReader(tc.in)); got != tc.want {
				t.Fatalf("defaultGatewayFrom(...) = %q, want %q", got, tc.want)
			}
		})
	}
}
