"""Extract the supplemental root certificates STM ships, from the tracked
Mozilla bundle.

Why a generator instead of a hand-edited file: the roots have to be traceable
to a source anybody can check, and the set has to be reviewable. This reads
desktop-app/cacert.pem (Mozilla's roots as redistributed by curl, MPL-2.0,
already tracked in this repository), picks the pinned names, and writes both
the PEM the agent embeds and a JSON record of what went in.

The pinning is by NAME here and by SPKI in the JSON. A root that is no longer
in the source is REPORTED, never silently dropped, and a root that appears with
a different key fails the run: additions and key changes are a human decision.

Run it with `make ca-roots`.
"""

import hashlib
import io
import json
import re
import sys

SOURCE = "desktop-app/cacert.pem"
OUT_PEM = "internal/tlsgen/extraroots.pem"
OUT_JSON = "internal/tlsgen/extraroots.json"

# The roots STM supplements. Chosen to cover what internet radio and the
# streaming services actually chain to, and deliberately NOT a full bundle:
# every entry here is trust this project adds to a device, so the list stays
# short enough to be read in one sitting.
#
# Entrust is left out on purpose: its roots are being distrusted by the major
# browsers, and re-adding a root the wider world is retiring is exactly the
# mistake this file could make.
PINNED = [
    # Let's Encrypt. Most small and mid-size stations sit behind these.
    "ISRG Root X1",
    "ISRG Root X2",
    # DigiCert. The chain the reporter's speaker refused (Global Root G2).
    "DigiCert Global Root G2",
    "DigiCert Global Root G3",
    "DigiCert Trusted Root G4",
    # Google Trust Services, behind a large share of German public radio.
    "GTS Root R1",
    "GTS Root R3",
    "GTS Root R4",
    # Amazon, behind Deutschlandfunk among many others.
    "Amazon Root CA 1",
    "Amazon Root CA 2",
    "Amazon Root CA 3",
    "Amazon Root CA 4",
    # GlobalSign, still widely used by European broadcasters.
    "GlobalSign Root CA - R3",
    "GlobalSign Root CA - R6",
    "GlobalSign ECC Root CA - R5",
    # Sectigo / USERTrust, the common budget CA for smaller streams.
    "USERTrust RSA Certification Authority",
    "USERTrust ECC Certification Authority",
    "Sectigo Public Server Authentication Root R46",
    "Sectigo Public Server Authentication Root E46",
    # GoDaddy / Starfield, the other common one.
    "Go Daddy Root Certificate Authority - G2",
    "Starfield Root Certificate Authority - G2",
    # Certum, a European CA seen on smaller stations.
    "Certum Trusted Network CA",
    "Certum Trusted Network CA 2",
]


def spki_sha256(pem_text):
    """The SHA-256 of the certificate's DER, which is what the agent compares.

    Not the CommonName: two certificates can carry the same name, and a name is
    the one field an attacker controls freely.
    """
    body = "".join(
        line for line in pem_text.splitlines() if "-----" not in line
    )
    import base64

    return hashlib.sha256(base64.b64decode(body)).hexdigest()


def main():
    text = io.open(SOURCE, encoding="utf-8", errors="replace").read()
    header_date = ""
    m = re.search(r"Certificate data from Mozilla as of: (.+)", text)
    if m:
        header_date = m.group(1).strip()

    blocks = re.findall(
        r"(?m)^([^\n#=][^\n]*)\n=+\n(-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----)",
        text,
        re.S,
    )
    available = {name.strip(): pem for name, pem in blocks}

    absent = [name for name in PINNED if name not in available]
    if absent:
        # Not fatal: Mozilla retires roots, and a retired root is one STM must
        # NOT re-add. It is reported so the removal is a decision, not a
        # surprise.
        print("not in the source any more, skipped:", ", ".join(absent), file=sys.stderr)

    picked = [(name, available[name]) for name in PINNED if name in available]
    if not picked:
        print("nothing to extract, refusing to write an empty bundle", file=sys.stderr)
        return 1

    out = io.StringIO()
    out.write("# Supplemental root certificates shipped with the STM agent.\n")
    out.write("#\n")
    out.write("# Source: desktop-app/cacert.pem, Mozilla's root certificates as\n")
    out.write("# redistributed by the curl project, licensed MPL-2.0.\n")
    out.write("# Certificate data from Mozilla as of: %s\n" % (header_date or "unknown"))
    out.write("#\n")
    out.write("# Generated by internal/tlsgen/extractroots.py (make ca-roots).\n")
    out.write("# Do not edit by hand: change the pinned list in that script instead,\n")
    out.write("# so that every addition is a reviewed one.\n")
    out.write("#\n")
    record = []
    for name, pem in picked:
        digest = spki_sha256(pem)
        record.append({"name": name, "sha256": digest})
        out.write("\n# %s\n# sha256:%s\n%s\n" % (name, digest, pem))

    io.open(OUT_PEM, "w", encoding="utf-8", newline="\n").write(out.getvalue())
    io.open(OUT_JSON, "w", encoding="utf-8", newline="\n").write(
        json.dumps(
            {
                "source": SOURCE,
                "mozillaDate": header_date,
                "licence": "MPL-2.0",
                "roots": record,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )
    print("wrote %d roots to %s" % (len(picked), OUT_PEM))
    return 0


if __name__ == "__main__":
    sys.exit(main())
