// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBoxByIP(arg1) {
  return window['go']['main']['App']['AddBoxByIP'](arg1);
}

export function AddMediaServerByURL(arg1) {
  return window['go']['main']['App']['AddMediaServerByURL'](arg1);
}

export function AnnounceExample(arg1, arg2) {
  return window['go']['main']['App']['AnnounceExample'](arg1, arg2);
}

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function BoxAgentVersion(arg1, arg2) {
  return window['go']['main']['App']['BoxAgentVersion'](arg1, arg2);
}

export function BoxForeignInfluence(arg1, arg2) {
  return window['go']['main']['App']['BoxForeignInfluence'](arg1, arg2);
}

export function BoxInstallReachable(arg1) {
  return window['go']['main']['App']['BoxInstallReachable'](arg1);
}

export function BoxPresets(arg1, arg2) {
  return window['go']['main']['App']['BoxPresets'](arg1, arg2);
}

export function BoxSSHStatus(arg1, arg2) {
  return window['go']['main']['App']['BoxSSHStatus'](arg1, arg2);
}

export function BoxSettings(arg1, arg2) {
  return window['go']['main']['App']['BoxSettings'](arg1, arg2);
}

export function BoxSnapshot(arg1, arg2) {
  return window['go']['main']['App']['BoxSnapshot'](arg1, arg2);
}

export function BoxSpeakerLevels(arg1, arg2) {
  return window['go']['main']['App']['BoxSpeakerLevels'](arg1, arg2);
}

export function BoxStoragePreflight(arg1, arg2) {
  return window['go']['main']['App']['BoxStoragePreflight'](arg1, arg2);
}

export function BoxWifiScan(arg1, arg2) {
  return window['go']['main']['App']['BoxWifiScan'](arg1, arg2);
}

export function BrowseLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowseLibrary'](arg1, arg2, arg3, arg4);
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function CheckStick(arg1) {
  return window['go']['main']['App']['CheckStick'](arg1);
}

export function ClassifyOTAResult(arg1, arg2) {
  return window['go']['main']['App']['ClassifyOTAResult'](arg1, arg2);
}

export function ClassifyStreamURL(arg1) {
  return window['go']['main']['App']['ClassifyStreamURL'](arg1);
}

export function ClearRecent(arg1, arg2) {
  return window['go']['main']['App']['ClearRecent'](arg1, arg2);
}

export function ClearUpdateIntent(arg1, arg2) {
  return window['go']['main']['App']['ClearUpdateIntent'](arg1, arg2);
}

export function CopyPresetsAcrossBoxes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CopyPresetsAcrossBoxes'](arg1, arg2, arg3, arg4);
}

export function CurrentWiFi() {
  return window['go']['main']['App']['CurrentWiFi']();
}

export function DeletePreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePreset'](arg1, arg2, arg3);
}

export function DeleteRecentCard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteRecentCard'](arg1, arg2, arg3, arg4);
}

export function DisableBoxMediaServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DisableBoxMediaServer'](arg1, arg2, arg3, arg4);
}

export function DiscoverBoxes(arg1) {
  return window['go']['main']['App']['DiscoverBoxes'](arg1);
}

export function DissolveStereoPair(arg1, arg2) {
  return window['go']['main']['App']['DissolveStereoPair'](arg1, arg2);
}

export function DissolveZone(arg1, arg2) {
  return window['go']['main']['App']['DissolveZone'](arg1, arg2);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function EjectDrive(arg1) {
  return window['go']['main']['App']['EjectDrive'](arg1);
}

export function EnableBoxMediaServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EnableBoxMediaServer'](arg1, arg2, arg3, arg4);
}

export function EnsureSpotifyEngine(arg1, arg2) {
  return window['go']['main']['App']['EnsureSpotifyEngine'](arg1, arg2);
}

export function ExportBackup(arg1) {
  return window['go']['main']['App']['ExportBackup'](arg1);
}

export function ExportDiagnosticLogs(arg1) {
  return window['go']['main']['App']['ExportDiagnosticLogs'](arg1);
}

export function ForgetPermanentGroup(arg1, arg2) {
  return window['go']['main']['App']['ForgetPermanentGroup'](arg1, arg2);
}

export function FormZone(arg1, arg2, arg3) {
  return window['go']['main']['App']['FormZone'](arg1, arg2, arg3);
}

export function FormatStick(arg1) {
  return window['go']['main']['App']['FormatStick'](arg1);
}

export function GetAirplayOpt(arg1, arg2) {
  return window['go']['main']['App']['GetAirplayOpt'](arg1, arg2);
}

export function GetAppFlag(arg1) {
  return window['go']['main']['App']['GetAppFlag'](arg1);
}

export function GetBoxFirmware(arg1) {
  return window['go']['main']['App']['GetBoxFirmware'](arg1);
}

export function GetBoxLanguage(arg1) {
  return window['go']['main']['App']['GetBoxLanguage'](arg1);
}

export function GetClockDisplay(arg1) {
  return window['go']['main']['App']['GetClockDisplay'](arg1);
}

export function GetClockFormat24(arg1) {
  return window['go']['main']['App']['GetClockFormat24'](arg1);
}

export function GetDisplayTrack(arg1, arg2) {
  return window['go']['main']['App']['GetDisplayTrack'](arg1, arg2);
}

export function GetGroupKeys(arg1, arg2) {
  return window['go']['main']['App']['GetGroupKeys'](arg1, arg2);
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetPresets(arg1, arg2) {
  return window['go']['main']['App']['GetPresets'](arg1, arg2);
}

export function GetQueue(arg1, arg2) {
  return window['go']['main']['App']['GetQueue'](arg1, arg2);
}

export function GetResumeOnPowerOn(arg1, arg2) {
  return window['go']['main']['App']['GetResumeOnPowerOn'](arg1, arg2);
}

export function GetStartVolume(arg1, arg2) {
  return window['go']['main']['App']['GetStartVolume'](arg1, arg2);
}

export function GetStereoPairName(arg1) {
  return window['go']['main']['App']['GetStereoPairName'](arg1);
}

export function GetWebhooks(arg1, arg2) {
  return window['go']['main']['App']['GetWebhooks'](arg1, arg2);
}

export function GetZoneState(arg1, arg2) {
  return window['go']['main']['App']['GetZoneState'](arg1, arg2);
}

export function ImportBackup() {
  return window['go']['main']['App']['ImportBackup']();
}

export function InstallSTMOnBox(arg1, arg2) {
  return window['go']['main']['App']['InstallSTMOnBox'](arg1, arg2);
}

export function IsBoseStick(arg1) {
  return window['go']['main']['App']['IsBoseStick'](arg1);
}

export function ListBoxMediaServers(arg1, arg2) {
  return window['go']['main']['App']['ListBoxMediaServers'](arg1, arg2);
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function ListMediaServers(arg1) {
  return window['go']['main']['App']['ListMediaServers'](arg1);
}

export function ListWiFiProfiles() {
  return window['go']['main']['App']['ListWiFiProfiles']();
}

export function LogClientError(arg1) {
  return window['go']['main']['App']['LogClientError'](arg1);
}

export function LogSpotifySaveGate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['LogSpotifySaveGate'](arg1, arg2, arg3, arg4, arg5);
}

export function MovePreset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MovePreset'](arg1, arg2, arg3, arg4);
}

export function Next(arg1, arg2) {
  return window['go']['main']['App']['Next'](arg1, arg2);
}

export function Pause(arg1, arg2) {
  return window['go']['main']['App']['Pause'](arg1, arg2);
}

export function PendingUpdateIntent(arg1, arg2) {
  return window['go']['main']['App']['PendingUpdateIntent'](arg1, arg2);
}

export function PhoneAddressFor(arg1, arg2) {
  return window['go']['main']['App']['PhoneAddressFor'](arg1, arg2);
}

export function PhoneQR(arg1) {
  return window['go']['main']['App']['PhoneQR'](arg1);
}

export function PlaySlot(arg1, arg2, arg3) {
  return window['go']['main']['App']['PlaySlot'](arg1, arg2, arg3);
}

export function PlayURL(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['PlayURL'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function Prev(arg1, arg2) {
  return window['go']['main']['App']['Prev'](arg1, arg2);
}

export function ProbeSetupAP() {
  return window['go']['main']['App']['ProbeSetupAP']();
}

export function ProbeTrackDelivery(arg1) {
  return window['go']['main']['App']['ProbeTrackDelivery'](arg1);
}

export function PushFavorites(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushFavorites'](arg1, arg2, arg3);
}

export function PushStereoPairNameToBox(arg1, arg2, arg3) {
  return window['go']['main']['App']['PushStereoPairNameToBox'](arg1, arg2, arg3);
}

export function PushWLANToBox(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PushWLANToBox'](arg1, arg2, arg3, arg4);
}

export function QueueNext(arg1, arg2) {
  return window['go']['main']['App']['QueueNext'](arg1, arg2);
}

export function QueuePrev(arg1, arg2) {
  return window['go']['main']['App']['QueuePrev'](arg1, arg2);
}

export function QueueRepeat(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueueRepeat'](arg1, arg2, arg3);
}

export function QueueShuffle(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueueShuffle'](arg1, arg2, arg3);
}

export function RadioCheckStream(arg1) {
  return window['go']['main']['App']['RadioCheckStream'](arg1);
}

export function RadioClick(arg1) {
  return window['go']['main']['App']['RadioClick'](arg1);
}

export function RadioLanguages(arg1, arg2) {
  return window['go']['main']['App']['RadioLanguages'](arg1, arg2);
}

export function RadioLookupForAdd(arg1, arg2) {
  return window['go']['main']['App']['RadioLookupForAdd'](arg1, arg2);
}

export function RadioPrecheckSubmit(arg1) {
  return window['go']['main']['App']['RadioPrecheckSubmit'](arg1);
}

export function RadioSearch(arg1) {
  return window['go']['main']['App']['RadioSearch'](arg1);
}

export function RadioSearchDetailed(arg1) {
  return window['go']['main']['App']['RadioSearchDetailed'](arg1);
}

export function RadioStationByUUID(arg1) {
  return window['go']['main']['App']['RadioStationByUUID'](arg1);
}

export function RadioStationsByURL(arg1) {
  return window['go']['main']['App']['RadioStationsByURL'](arg1);
}

export function RadioSubmitStation(arg1, arg2) {
  return window['go']['main']['App']['RadioSubmitStation'](arg1, arg2);
}

export function RadioTags(arg1) {
  return window['go']['main']['App']['RadioTags'](arg1);
}

export function RadioVote(arg1) {
  return window['go']['main']['App']['RadioVote'](arg1);
}

export function RebootBox(arg1, arg2) {
  return window['go']['main']['App']['RebootBox'](arg1, arg2);
}

export function RecallBoxPreset(arg1, arg2, arg3) {
  return window['go']['main']['App']['RecallBoxPreset'](arg1, arg2, arg3);
}

export function RecentPlayed(arg1, arg2) {
  return window['go']['main']['App']['RecentPlayed'](arg1, arg2);
}

export function RecordOTAOutcome(arg1, arg2) {
  return window['go']['main']['App']['RecordOTAOutcome'](arg1, arg2);
}

export function RecordUpdateIntent(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RecordUpdateIntent'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RefreshKnownBoxes() {
  return window['go']['main']['App']['RefreshKnownBoxes']();
}

export function RemoveConflictingMod(arg1, arg2) {
  return window['go']['main']['App']['RemoveConflictingMod'](arg1, arg2);
}

export function RemoveGroupMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveGroupMember'](arg1, arg2, arg3);
}

export function RemoveManualMediaServer(arg1) {
  return window['go']['main']['App']['RemoveManualMediaServer'](arg1);
}

export function RenamePreset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenamePreset'](arg1, arg2, arg3, arg4);
}

export function RepairInstallViaSSH(arg1, arg2) {
  return window['go']['main']['App']['RepairInstallViaSSH'](arg1, arg2);
}

export function ReplayFolderCard(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ReplayFolderCard'](arg1, arg2, arg3, arg4, arg5);
}

export function RescuedSpeakerCount() {
  return window['go']['main']['App']['RescuedSpeakerCount']();
}

export function ResolveStationLogo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveStationLogo'](arg1, arg2, arg3);
}

export function ResolveUpdateAsset(arg1) {
  return window['go']['main']['App']['ResolveUpdateAsset'](arg1);
}

export function RestoreBoxSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreBoxSnapshot'](arg1, arg2, arg3);
}

export function RestoreGroupAfterUpdate(arg1, arg2) {
  return window['go']['main']['App']['RestoreGroupAfterUpdate'](arg1, arg2);
}

export function RestoreSTMCloud(arg1) {
  return window['go']['main']['App']['RestoreSTMCloud'](arg1);
}

export function Resume(arg1, arg2) {
  return window['go']['main']['App']['Resume'](arg1, arg2);
}

export function RevealUpdateFile(arg1) {
  return window['go']['main']['App']['RevealUpdateFile'](arg1);
}

export function SaveDiagnosticBundle(arg1, arg2) {
  return window['go']['main']['App']['SaveDiagnosticBundle'](arg1, arg2);
}

export function SaveFolderPreset(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFolderPreset'](arg1, arg2, arg3, arg4);
}

export function SaveGroupKeys(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveGroupKeys'](arg1, arg2, arg3);
}

export function SaveLibraryPreset(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveLibraryPreset'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveSpotifyPreset(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveSpotifyPreset'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveWebhookConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveWebhookConfig'](arg1, arg2, arg3);
}

export function SelectBoxSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SelectBoxSource'](arg1, arg2, arg3, arg4);
}

export function SendAnnounce(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendAnnounce'](arg1, arg2, arg3, arg4, arg5);
}

export function SetAirplayOpt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAirplayOpt'](arg1, arg2, arg3);
}

export function SetAppFlag(arg1) {
  return window['go']['main']['App']['SetAppFlag'](arg1);
}

export function SetAppLocale(arg1) {
  return window['go']['main']['App']['SetAppLocale'](arg1);
}

export function SetBoxBass(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBoxBass'](arg1, arg2, arg3);
}

export function SetBoxLanguage(arg1, arg2) {
  return window['go']['main']['App']['SetBoxLanguage'](arg1, arg2);
}

export function SetBoxName(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBoxName'](arg1, arg2, arg3);
}

export function SetBoxSSHPersistent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBoxSSHPersistent'](arg1, arg2, arg3);
}

export function SetBoxSpeakerLevel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetBoxSpeakerLevel'](arg1, arg2, arg3, arg4);
}

export function SetBoxVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBoxVolume'](arg1, arg2, arg3);
}

export function SetClockDisplay(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetClockDisplay'](arg1, arg2, arg3, arg4, arg5);
}

export function SetDisplayTrack(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetDisplayTrack'](arg1, arg2, arg3, arg4);
}

export function SetOTARunning(arg1) {
  return window['go']['main']['App']['SetOTARunning'](arg1);
}

export function SetPreset(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SetPreset'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SetResumeOnPowerOn(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetResumeOnPowerOn'](arg1, arg2, arg3);
}

export function SetSpotifyQuality(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSpotifyQuality'](arg1, arg2, arg3);
}

export function SetStartVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetStartVolume'](arg1, arg2, arg3);
}

export function SetStereoPairName(arg1, arg2) {
  return window['go']['main']['App']['SetStereoPairName'](arg1, arg2);
}

export function SetWebhooks(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SetWebhooks'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SpotifyBitrate(arg1, arg2) {
  return window['go']['main']['App']['SpotifyBitrate'](arg1, arg2);
}

export function SpotifyNowPlaying(arg1, arg2) {
  return window['go']['main']['App']['SpotifyNowPlaying'](arg1, arg2);
}

export function SpotifyQuality(arg1, arg2) {
  return window['go']['main']['App']['SpotifyQuality'](arg1, arg2);
}

export function StartQueue(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartQueue'](arg1, arg2, arg3);
}

export function Status(arg1, arg2) {
  return window['go']['main']['App']['Status'](arg1, arg2);
}

export function StickConfigs(arg1) {
  return window['go']['main']['App']['StickConfigs'](arg1);
}

export function StickVersion(arg1) {
  return window['go']['main']['App']['StickVersion'](arg1);
}

export function Stop(arg1, arg2) {
  return window['go']['main']['App']['Stop'](arg1, arg2);
}

export function StreamBitrate(arg1, arg2) {
  return window['go']['main']['App']['StreamBitrate'](arg1, arg2);
}

export function StreamTitle(arg1, arg2) {
  return window['go']['main']['App']['StreamTitle'](arg1, arg2);
}

export function SuggestBoxLanguage(arg1, arg2) {
  return window['go']['main']['App']['SuggestBoxLanguage'](arg1, arg2);
}

export function SwitchBoxWLAN(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SwitchBoxWLAN'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SyncBoxPresets(arg1, arg2) {
  return window['go']['main']['App']['SyncBoxPresets'](arg1, arg2);
}

export function SyncSpotifyLogin(arg1) {
  return window['go']['main']['App']['SyncSpotifyLogin'](arg1);
}

export function TestWebhook(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TestWebhook'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestWebhookAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestWebhookAction'](arg1, arg2, arg3);
}

export function TrackPosition(arg1, arg2) {
  return window['go']['main']['App']['TrackPosition'](arg1, arg2);
}

export function Translate(arg1, arg2) {
  return window['go']['main']['App']['Translate'](arg1, arg2);
}

export function TrueFactoryReset(arg1) {
  return window['go']['main']['App']['TrueFactoryReset'](arg1);
}

export function TryWiFiPassword(arg1) {
  return window['go']['main']['App']['TryWiFiPassword'](arg1);
}

export function TuneInBrowse(arg1) {
  return window['go']['main']['App']['TuneInBrowse'](arg1);
}

export function TuneInListenURL(arg1) {
  return window['go']['main']['App']['TuneInListenURL'](arg1);
}

export function TuneInResolveShare(arg1) {
  return window['go']['main']['App']['TuneInResolveShare'](arg1);
}

export function TuneInSearch(arg1) {
  return window['go']['main']['App']['TuneInSearch'](arg1);
}

export function TuneInStationInfo(arg1) {
  return window['go']['main']['App']['TuneInStationInfo'](arg1);
}

export function UndoForeignFinding(arg1, arg2, arg3) {
  return window['go']['main']['App']['UndoForeignFinding'](arg1, arg2, arg3);
}

export function UninstallSTM(arg1) {
  return window['go']['main']['App']['UninstallSTM'](arg1);
}

export function UpdateBoxAgent(arg1, arg2) {
  return window['go']['main']['App']['UpdateBoxAgent'](arg1, arg2);
}

export function UpdateFailureReport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateFailureReport'](arg1, arg2, arg3, arg4, arg5);
}

export function WakeBox(arg1, arg2) {
  return window['go']['main']['App']['WakeBox'](arg1, arg2);
}

export function WriteLangConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteLangConfig'](arg1, arg2, arg3, arg4);
}

export function WriteNameConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteNameConfig'](arg1, arg2);
}

export function WriteRegionConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteRegionConfig'](arg1, arg2);
}

export function WriteStickFiles(arg1) {
  return window['go']['main']['App']['WriteStickFiles'](arg1);
}

export function WriteWLANConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteWLANConfig'](arg1, arg2, arg3);
}
