// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {sticksetup} from '../models';
import {wifiprofiles} from '../models';
import {streamcheck} from '../models';
import {radiobrowser} from '../models';
import {tunein} from '../models';

export function AddBoxByIP(arg1:string):Promise<main.BoxInfo>;

export function AddMediaServerByURL(arg1:string):Promise<main.LibraryServer>;

export function AnnounceExample(arg1:string,arg2:number):Promise<string>;

export function AppInfo():Promise<main.AppInfo>;

export function AppVersion():Promise<string>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function BoxAgentVersion(arg1:string,arg2:number):Promise<Record<string, string>>;

export function BoxForeignInfluence(arg1:string,arg2:number):Promise<Record<string, any>>;

export function BoxInstallReachable(arg1:string):Promise<boolean>;

export function BoxPresets(arg1:string,arg2:number):Promise<Array<main.BoxPresetInfo>>;

export function BoxSSHStatus(arg1:string,arg2:number):Promise<main.BoxSSHState>;

export function BoxSettings(arg1:string,arg2:number):Promise<Record<string, any>>;

export function BoxSnapshot(arg1:string,arg2:number):Promise<Record<string, any>>;

export function BoxSpeakerLevels(arg1:string,arg2:number):Promise<Record<string, any>>;

export function BoxStoragePreflight(arg1:string,arg2:number):Promise<main.StoragePreflight>;

export function BoxWifiScan(arg1:string,arg2:number):Promise<Array<string>>;

export function BrowseLibrary(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.LibraryPage>;

export function CheckAppUpdate():Promise<Record<string, string>>;

export function CheckStick(arg1:string):Promise<sticksetup.StickCheck>;

export function ClassifyOTAResult(arg1:string,arg2:number):Promise<string>;

export function ClassifyStreamURL(arg1:string):Promise<main.StreamURLKind>;

export function ClearRecent(arg1:string,arg2:number):Promise<void>;

export function ClearUpdateIntent(arg1:string,arg2:number):Promise<void>;

export function CopyPresetsAcrossBoxes(arg1:string,arg2:number,arg3:string,arg4:number):Promise<number>;

export function CurrentWiFi():Promise<string>;

export function DeletePreset(arg1:string,arg2:number,arg3:number):Promise<void>;

export function DeleteRecentCard(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function DisableBoxMediaServer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function DiscoverBoxes(arg1:number):Promise<Array<main.BoxInfo>>;

export function DissolveStereoPair(arg1:string,arg2:number):Promise<void>;

export function DissolveZone(arg1:string,arg2:number):Promise<Record<string, any>>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function EjectDrive(arg1:string):Promise<void>;

export function EnableBoxMediaServer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function EnsureSpotifyEngine(arg1:string,arg2:number):Promise<string>;

export function ExportBackup(arg1:string):Promise<Record<string, any>>;

export function ExportDiagnosticLogs(arg1:main.LogExportRequest):Promise<main.LogExportResult>;

export function ForgetPermanentGroup(arg1:string,arg2:number):Promise<Record<string, any>>;

export function FormZone(arg1:string,arg2:number,arg3:main.ZoneSpec):Promise<Record<string, any>>;

export function FormatStick(arg1:string):Promise<void>;

export function GetAirplayOpt(arg1:string,arg2:number):Promise<Record<string, boolean>>;

export function GetAppFlag(arg1:string):Promise<boolean>;

export function GetBoxFirmware(arg1:string):Promise<main.FirmwareInfo>;

export function GetBoxLanguage(arg1:string):Promise<string>;

export function GetClockDisplay(arg1:string):Promise<string>;

export function GetClockFormat24(arg1:string):Promise<boolean>;

export function GetDisplayTrack(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetGroupKeys(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetLogFilePath():Promise<string>;

export function GetPresets(arg1:string,arg2:number):Promise<Array<main.Preset>>;

export function GetQueue(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetResumeOnPowerOn(arg1:string,arg2:number):Promise<Record<string, boolean>>;

export function GetStartVolume(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetStereoPairName(arg1:string):Promise<string>;

export function GetWebhooks(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetZoneState(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ImportBackup():Promise<Record<string, any>>;

export function InstallSTMOnBox(arg1:string,arg2:string):Promise<main.InstallResult>;

export function IsBoseStick(arg1:string):Promise<boolean>;

export function ListBoxMediaServers(arg1:string,arg2:number):Promise<Array<main.BoxMediaServer>>;

export function ListDrives():Promise<Array<sticksetup.Drive>>;

export function ListMediaServers(arg1:number):Promise<Array<main.LibraryServer>>;

export function ListWiFiProfiles():Promise<Array<wifiprofiles.Profile>>;

export function LogClientError(arg1:string):Promise<void>;

export function LogSpotifySaveGate(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function MovePreset(arg1:string,arg2:number,arg3:number,arg4:number):Promise<void>;

export function Next(arg1:string,arg2:number):Promise<void>;

export function Pause(arg1:string,arg2:number):Promise<void>;

export function PendingUpdateIntent(arg1:string,arg2:number):Promise<Record<string, string>>;

export function PhoneAddressFor(arg1:string,arg2:number):Promise<main.PhoneAddress>;

export function PhoneQR(arg1:string):Promise<string>;

export function PlaySlot(arg1:string,arg2:number,arg3:number):Promise<void>;

export function PlayURL(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:number):Promise<void>;

export function Prev(arg1:string,arg2:number):Promise<void>;

export function ProbeSetupAP():Promise<main.BoxInfo|boolean>;

export function ProbeTrackDelivery(arg1:string):Promise<main.TrackDelivery>;

export function PushFavorites(arg1:string,arg2:number,arg3:string):Promise<void>;

export function PushStereoPairNameToBox(arg1:string,arg2:number,arg3:string):Promise<void>;

export function PushWLANToBox(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.SetupAPPushResult>;

export function QueueNext(arg1:string,arg2:number):Promise<void>;

export function QueuePrev(arg1:string,arg2:number):Promise<void>;

export function QueueRepeat(arg1:string,arg2:number,arg3:string):Promise<void>;

export function QueueShuffle(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function RadioCheckStream(arg1:string):Promise<streamcheck.Result>;

export function RadioClick(arg1:string):Promise<void>;

export function RadioLanguages(arg1:string,arg2:number):Promise<Array<radiobrowser.Language>>;

export function RadioLookupForAdd(arg1:string,arg2:string):Promise<Array<main.RadioStationStatus>>;

export function RadioPrecheckSubmit(arg1:main.RadioSubmitDraft):Promise<main.RadioSubmitPrecheck>;

export function RadioSearch(arg1:main.RadioSearchOpts):Promise<Array<radiobrowser.Station>>;

export function RadioSearchDetailed(arg1:main.RadioSearchOpts):Promise<main.RadioSearchResult>;

export function RadioStationByUUID(arg1:string):Promise<main.RadioStationLookup>;

export function RadioStationsByURL(arg1:string):Promise<Array<radiobrowser.Station>>;

export function RadioSubmitStation(arg1:main.RadioSubmitDraft,arg2:boolean):Promise<main.RadioSubmitResult>;

export function RadioTags(arg1:number):Promise<Array<radiobrowser.Tag>>;

export function RadioVote(arg1:string):Promise<void>;

export function RebootBox(arg1:string,arg2:number):Promise<void>;

export function RecallBoxPreset(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RecentPlayed(arg1:string,arg2:number):Promise<Array<main.RecentItem>>;

export function RecordOTAOutcome(arg1:string,arg2:string):Promise<void>;

export function RecordUpdateIntent(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function RefreshKnownBoxes():Promise<Array<main.BoxInfo>>;

export function RemoveConflictingMod(arg1:string,arg2:number):Promise<string>;

export function RemoveGroupMember(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function RemoveManualMediaServer(arg1:string):Promise<void>;

export function RenamePreset(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function RepairInstallViaSSH(arg1:string,arg2:string):Promise<main.InstallResult>;

export function ReplayFolderCard(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RescuedSpeakerCount():Promise<number>;

export function ResolveStationLogo(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function ResolveUpdateAsset(arg1:string):Promise<main.UpdateAsset>;

export function RestoreBoxSnapshot(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function RestoreGroupAfterUpdate(arg1:string,arg2:number):Promise<void>;

export function RestoreSTMCloud(arg1:Array<main.CloudRestoreTarget>):Promise<Array<main.CloudRestoreResult>>;

export function Resume(arg1:string,arg2:number):Promise<void>;

export function RevealUpdateFile(arg1:string):Promise<void>;

export function SaveDiagnosticBundle(arg1:Array<string>,arg2:boolean):Promise<main.LogExportResult>;

export function SaveFolderPreset(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function SaveGroupKeys(arg1:string,arg2:number,arg3:Record<string, any>):Promise<void>;

export function SaveLibraryPreset(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string,arg7:number,arg8:string):Promise<void>;

export function SaveSpotifyPreset(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SaveWebhookConfig(arg1:string,arg2:number,arg3:Record<string, any>):Promise<void>;

export function SelectBoxSource(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SendAnnounce(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number):Promise<void>;

export function SetAirplayOpt(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetAppFlag(arg1:string):Promise<void>;

export function SetAppLocale(arg1:string):Promise<void>;

export function SetBoxBass(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetBoxLanguage(arg1:string,arg2:number):Promise<void>;

export function SetBoxName(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetBoxSSHPersistent(arg1:string,arg2:number,arg3:boolean):Promise<main.BoxSSHState>;

export function SetBoxSpeakerLevel(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function SetBoxVolume(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetClockDisplay(arg1:string,arg2:boolean,arg3:string,arg4:number,arg5:boolean):Promise<void>;

export function SetDisplayTrack(arg1:string,arg2:number,arg3:boolean,arg4:string):Promise<void>;

export function SetOTARunning(arg1:boolean):Promise<void>;

export function SetPreset(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string,arg7:number,arg8:string,arg9:string):Promise<void>;

export function SetResumeOnPowerOn(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetSpotifyQuality(arg1:string,arg2:number,arg3:number):Promise<main.SpotifyQualityState>;

export function SetStartVolume(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetStereoPairName(arg1:string,arg2:string):Promise<void>;

export function SetWebhooks(arg1:string,arg2:number,arg3:boolean,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function SpotifyBitrate(arg1:string,arg2:number):Promise<number>;

export function SpotifyNowPlaying(arg1:string,arg2:number):Promise<main.SpotifyNow>;

export function SpotifyQuality(arg1:string,arg2:number):Promise<main.SpotifyQualityState>;

export function StartQueue(arg1:string,arg2:number,arg3:string):Promise<void>;

export function Status(arg1:string,arg2:number):Promise<string>;

export function StickConfigs(arg1:string):Promise<sticksetup.StickConfigs>;

export function StickVersion(arg1:string):Promise<string>;

export function Stop(arg1:string,arg2:number):Promise<void>;

export function StreamBitrate(arg1:string,arg2:number):Promise<number>;

export function StreamTitle(arg1:string,arg2:number):Promise<string>;

export function SuggestBoxLanguage(arg1:string,arg2:string):Promise<number>;

export function SyncBoxPresets(arg1:string,arg2:number):Promise<Record<string, any>>;

export function SyncSpotifyLogin(arg1:Array<main.SpotifySyncTarget>):Promise<Record<string, any>>;

export function TestWebhook(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function TestWebhookAction(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function TrackPosition(arg1:string,arg2:number):Promise<number|number>;

export function Translate(arg1:string,arg2:string):Promise<string>;

export function TrueFactoryReset(arg1:string):Promise<main.TrueFactoryResetResult>;

export function TryWiFiPassword(arg1:string):Promise<string>;

export function TuneInBrowse(arg1:string):Promise<tunein.Page>;

export function TuneInListenURL(arg1:string):Promise<main.TuneInListen>;

export function TuneInResolveShare(arg1:string):Promise<main.TuneInStation>;

export function TuneInSearch(arg1:string):Promise<tunein.Page>;

export function TuneInStationInfo(arg1:string):Promise<main.TuneInStation>;

export function UndoForeignFinding(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function UninstallSTM(arg1:string):Promise<main.UninstallSTMResult>;

export function UpdateBoxAgent(arg1:string,arg2:number):Promise<void>;

export function UpdateFailureReport(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function WakeBox(arg1:string,arg2:number):Promise<void>;

export function WriteLangConfig(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function WriteNameConfig(arg1:string,arg2:string):Promise<void>;

export function WriteRegionConfig(arg1:string,arg2:string):Promise<void>;

export function WriteStickFiles(arg1:string):Promise<Array<string>>;

export function WriteWLANConfig(arg1:string,arg2:string,arg3:string):Promise<void>;
